# config file for labeler action
# for documentation see https://github.com/actions/labeler

# add label stable to stable PRs
Stable:
- any: ['sources-dist-stable.json']

CHANGES-BOTH-REPOSITORIES:
- any: ['sources-dist.json']
  any: ['sources-dist-stable.json']
