name: Check npm access

on:
  schedule:
    # * is a special character in YAML, so you have to quote this string
    # every sunday at 3:33
    - cron:  '55 * * * *'

jobs:
  check-npms:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i
      - run: npm run checkNpm
        env:
          OWN_GITHUB_TOKEN: ${{ secrets.OWN_GITHUB_TOKEN }}
