# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.

name: Set labels

on:
  pull_request_target:
    types: [opened, edited, ready_for_review, reopened, labeled, unlabeled]
  issue_comment:
    types: [created, edited]
    
jobs:
  setLabels:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i
      - run: npm run setLabels
        env:
          OWN_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
